# Generated by Django 4.0.5 on 2022-06-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
