# Generated by Django 4.0.5 on 2022-06-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0004_alter_wish_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='Wisher',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wishApp.user'),
            preserve_default=False,
        ),
    ]
