# Generated by Django 4.0.5 on 2022-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0007_wish_wisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Wisher',
        ),
        migrations.AlterField(
            model_name='wish',
            name='Like',
            field=models.IntegerField(),
        ),
    ]
