<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lName',
        ),
    ]
=======
# Generated by Django 4.0.5 on 2022-06-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lName',
        ),
    ]
>>>>>>> e952974c77d98ff495761fdcef6ddcc990316774
