<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_books_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='update',
        ),
    ]
=======
# Generated by Django 4.0.5 on 2022-06-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_books_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='update',
        ),
    ]
>>>>>>> e952974c77d98ff495761fdcef6ddcc990316774
