<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_remove_books_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
    ]
=======
# Generated by Django 4.0.5 on 2022-06-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_remove_books_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
    ]
>>>>>>> e952974c77d98ff495761fdcef6ddcc990316774
