# Generated by Django 4.0.5 on 2022-06-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0008_remove_wish_wisher_alter_wish_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Like',
        ),
        migrations.AddField(
            model_name='user',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='Wisher',
            field=models.CharField(default='mohammed', max_length=255),
            preserve_default=False,
        ),
    ]
