# Generated by Django 4.0.5 on 2022-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0009_remove_wish_like_user_granted_wish_wisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='granted',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='Wisher',
        ),
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
