# Generated by Django 4.0.5 on 2022-06-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0010_remove_user_granted_remove_wish_wisher_wish_granted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wishers',
        ),
    ]
