# Generated by Django 4.0.5 on 2022-06-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0011_remove_wish_granted_remove_wish_wishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='created',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='des',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='updated_at',
        ),
    ]
