<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='des',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 4.0.5 on 2022-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='des',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
>>>>>>> e952974c77d98ff495761fdcef6ddcc990316774
